export const QUIZ_KEYWORDS: string[] = [
  /* ================= AI ================= */
  "intelligent agent",
  "performance measure",
  "agent function",
  "uninformed search",
  "informed search",
  "heuristic function",
  "propositional logic",
  "first order logic",
  "inference mechanism",
  "classical planning",
  "planning graph",
  "strips",
  "machine learning",
  "supervised learning",
  "unsupervised learning",

  /* ================= ML ================= */
  "linear regression",
  "multiple regression",
  "gradient descent",
  "logistic regression",
  "decision tree",
  "k-nearest neighbors",
  "k-means",
  "hierarchical clustering",
  "bias variance tradeoff",
  "cross validation",
  "performance metrics",

  /* ================= SE ================= */
  /* ================= SE ================= */
"software process",
"software process model",
"waterfall model",
"incremental model",
"spiral model",
"agile model",
"agile",
"verification",
"validation",
"srs",
"uml",
"software testing",


  /* ================= DS ================= */
  "data structure",
  "algorithm analysis",
  "array",
  "stack",
  "queue",
  "binary tree",
  "binary search tree",
  "tree traversal",
  "graph",
  "graph traversal",
  "hash table",
  "collision resolution",

  /* ================= OOP ================= */
  "oop concept",
  "class",
  "object",
  "inheritance",
  "method overriding",
  "polymorphism",
  "compile time polymorphism",
  "runtime polymorphism",
  "abstraction",
  "abstract class",
  "interface",
  "exception handling",

  /* ================= CO ================= */
  "instruction set architecture",
  "cpu organization",
  "instruction cycle",
  "pipelining",
  "pipeline hazard",
  "memory hierarchy",
  "cache memory",
  "input output organization",
  "interrupt",

  /* ================= CN ================= */
  "osi model",
  "tcp ip",
  "ip addressing",
  "tcp",
  "udp",
  "congestion control",
  "routing algorithm",
  "distance vector",
  "link state",
  "http",
  "ftp",
  "dns",

  /* ================= OS ================= */
  "operating system",
  "system call",
  "process management",
  "cpu scheduling",
  "deadlock",
  "deadlock prevention",
  "deadlock avoidance",
  "paging",
  "virtual memory",
  "file system",
  "disk scheduling",

  /* ================= DBMS ================= */
  "dbms architecture",
  "er model",
  "relational model",
  "sql",
  "join",
  "subquery",
  "functional dependency",
  "normalization",
  "indexing",
  "transaction management",

  /* Computer Networks */
"local area network",
"metropolitan area network",
"wide area network",
"personal area network",
"lan",
"man",
"wan",
"pan",

];
